### PR TITLE
Release0321: Re-branding | Embedded | Magento 2.4 support

### PR DESCRIPTION
**Pull request by MaksymGrom**

### CODE REVIEW

**Comment by simonworkhouse** [comment]
Changing the namespace like this would break any existing integrations and would also require re-configuring the module.

Can I take this as a hint that this may be the intended direction of this package?

**Comment by MaksymGrom** [comment]
> Changing the namespace like this would break any existing integrations and would also require re-configuring the module.
> 
> Can I take this as a hint that this may be the intended direction of this package?

I've warned that Namespaces is not backward compatible. As I know it is going to have a new version or even a new package

**Comment by MaksymGrom** [comment]
Namespace changing has been reverted

**Comment by MaksymGrom** [comment]
> Changing the namespace like this would break any existing integrations and would also require re-configuring the module.
> 
> Can I take this as a hint that this may be the intended direction of this package?

Changes of namespace have been reverted.
So the package is backward compatible and no need to re-configure after an update

**Pull request merged**
